sudo: false
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
install:
  - pip install importlib_resources
  - pip install requests
  - pip install codecov
  - pip install coverage
script:
  - python -m unittest discover
  - coverage run -m unittest discover
after_success:
  - codecov
