sudo: false
language: python
python:
  - "3.7"
install:
  - pip install importlib_resources
  - pip install requests
  - pip install codecov
  - pip install coverage
script:
  - python -m unittest discover
  - coverage run -m unittest discover
after_success:
  - codecov
