sudo: false
dist: xenial   # required for Python >= 3.7
language: python
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
install:
  - pip install requests
  - pip install --editable .
  - pip install flake8
script:
  - flake8
  - python -m unittest discover
